<?php
    $employee = $block->getEmployee();
?>

<table>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Department</th>
        </tr>
        <?php foreach ($employee as $item) :?>
            <tr>
                <td> <?= $item->getData('entity_id') ?> </td>
                <td> <?= $item->getData('firstname') ?> </td>
                <td> <?= $item->getData('lastname') ?> </td>
                <td> <?= $item->getData('email') ?> </td>
                <td><?= $item->getDepartment()->getName() ?> </td>
            </tr>
        <?php endforeach; ?>
</table>